version: 2

updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: monthly
    groups:
      android-runtime:
        patterns:
          - "androidx.*"
          - "com.google.android.*"
          - "com.google.dagger:*"
      kotlin-tooling:
        patterns:
          - "org.jetbrains.kotlin*"
          - "com.google.devtools.ksp*"
          - "io.gitlab.arturbosch.detekt*"
          - "org.jlleitschuh.gradle.ktlint*"
      tests:
        dependency-type: development
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      actions:
        patterns:
          - "*"
